CREATE TABLE TB_PF_ARTIST (
    ARTIST_ID INT IDENTITY(1,1) NOT NULL,
    NAME NVARCHAR(50),
    BIRTH DATE,
    AGENCY NVARCHAR(50),
    NATIONALITY NVARCHAR(50),
    INTRODUCTION NVARCHAR(MAX),
    REGISTRANT NVARCHAR(50),
    CREATED_AT DATETIME2,
    UPDATED_AT DATETIME2,
    CONSTRAINT PK_TB_PF_ARTIST PRIMARY KEY (ARTIST_ID)
)
GO

CREATE TABLE TB_PF_ALBUM (
      ALBUM_ID INT IDENTITY(1,1) NOT NULL,
      ARTIST_ID INT NOT NULL,
      TITLE NVARCHAR(100),
      RELEASE_DATE DATE,
      GENRE NVARCHAR(50),
      DESCRIPTION NVARCHAR(MAX),
      REGISTRANT NVARCHAR(50),
      CREATED_AT DATETIME2,
      UPDATED_AT DATETIME2,
      CONSTRAINT PK_TB_PF_ALBUM PRIMARY KEY (ALBUM_ID),
      CONSTRAINT FK_TB_PF_ALBUM_ARTIST FOREIGN KEY (ARTIST_ID) REFERENCES TB_PF_ARTIST(ARTIST_ID)
)
GO

CREATE TABLE TB_PF_SOUNDTRACK (
     TRACK_ID INT IDENTITY(1,1) NOT NULL,
     ALBUM_ID INT NOT NULL,
     TRACK_NO INT,
     TITLE NVARCHAR(100),
     PLAY_TIME NVARCHAR(100),
     EXPOSURE BIT,
     CREATED_AT DATETIME2,
     UPDATED_AT DATETIME2,
     CONSTRAINT PK_TB_PF_SOUNDTRACK PRIMARY KEY (TRACK_ID),
     CONSTRAINT FK_TB_PF_SOUNDTRACK_ALBUM FOREIGN KEY (ALBUM_ID) REFERENCES TB_PF_ALBUM(ALBUM_ID)
)
GO