IF NOT EXISTS(SELECT ARTIST_ID FROM TB_PF_ARTIST WHERE ARTIST_ID = 1)
    BEGIN
        SET IDENTITY_INSERT TB_PF_ARTIST ON
        INSERT INTO TB_PF_ARTIST (ARTIST_ID, NAME, BIRTH, AGENCY, NATIONALITY, INTRODUCTION, REGISTRANT, CREATED_AT, UPDATED_AT)
        VALUES (1, N'아이유', '1993-05-16', N'이담엔터테인먼트', N'한국', N'아이유는 베스트셀러이자 스테디셀러', 'aslan', GETDATE(), GETDATE())
        SET IDENTITY_INSERT TB_PF_ARTIST OFF
    END;
